#!/bin/sh

#LEPTON_IP1=10.105.47.137
#LEPTON_IP2=10.105.47.111

LEPTON_IP1=l1
LEPTON_IP2=l2

LOCAL_DATA_ROOT=./lepton-data
LOCAL_DATA_DIR1=$LOCAL_DATA_ROOT/1
LOCAL_DATA_DIR2=$LOCAL_DATA_ROOT/2

REMOTE_DATA_ROOT=/home/pi/lepton-data/

mkdir -p $LOCAL_DATA_DIR1
#mkdir -p $LOCAL_DATA_DIR2

rsync -rv pi@$LEPTON_IP1:$REMOTE_DATA_ROOT $LOCAL_DATA_DIR1
#rsync -rv pi@$LEPTON_IP2:$REMOTE_DATA_ROOT $LOCAL_DATA_DIR2
